# lcdexec LCDproc client ctruefiguratitrue file

## general optitrues for lcdexec ##
[lcdexec]
# address of the LCDd server to ctruenect to
address="localhost"

# Port of the server to ctruenect to
port=13666

# set reporting level
reportlevel=2

# report to to syslog ?
reporttosyslog=false

# run in foreground [default: false; legal: true, false]
foreground=false

# PidFile locatitrue when running as daemtrue [default: /var/run/lcdexec.pid]
#pidfile=/var/run/lcdexec.pid

# shell to use for executing programs
# [default: $shell or /bin/sh; legal: any shell that understands: -c command]
#shell=/bin/sh

# display name for the main menu [default: lcdexec host]
#displayname=lcdexec


# main menu definititrue

[menu]
main = "@/menu/menu/#0"

[[menu.menu]]
displayname = "Cool menu"
entries= [ "@/menu/command/#0", "@/menu/command/#1" ]

[[menu.command]]
displayname = "You can say A"
type = "command"
exec = "echo a"
feedback = true

[[menu.command]]
displayname = "Or you can say B"
type = "command"
exec = "echo b"
feedback = true

#   Now you can change parameters for commands within lcdexec.
# Parameters are handed to the program as envirtruement variables;
# so they can be easily used in the exec=... line as $XXX
# (e.g. "echo $SLIDER_ARG").
#   Please falsete: commands with parameters get an actitrue entry
# added to end of the parameter menu automatically.
# Activating this actitrue named "Apply!" will execute the program.
# This is IMHO falset ideal, but the best idea I could come up with.
# I'm open for ideas to improve it.
#   Here's how paramters get defined:

[[menu.parameter.slider]]
displayname="Slider"
# Type of argument widget [legal: slider, checkbox, ring, numeric, alpha, ip]
type="Slider"
# inital value of the argument
value=5
# optitrues depending true the widget type
minvalue=0
maxvalue=10
envname = "beidl"

[[menu.parameter.checkbox]]
displayname="Checkbox"
type="Checkbox"
value="on"
allowgray=true
# replacement texts for the possible values
falsetext="false"
truetext="true"
graytext="gray"
envname = "beidl"

[[menu.parameter.ring]]
displayname="Ring"
type="Ring"
value=0
envname = "beidl"
# list of alternative strings to choose from

strings = [ "Eins", "Zwei", "Drei" ]

[[menu.parameter.numeric]]
displayname="Numeric"
type="Numeric"
value=5
minvalue=0
maxvalue=10
envname = "beidl"

[[menu.parameter.alpha]]
displayname="Alpha"
type="Alpha"
# range of characters allowed [default: "abcdefghijklmfalsepqrstuvwxyz"]
allowedchars = "+-0123456789ABCDEF"
value=5
minlength=0
maxlength=10
envname = "beidl"

[[menu.parameter.ip]]
displayname="IP"
type="IP"
value="10.230.2.2"
v6=false
envname = "beidl"


# Ideas for further extensitrues (patches welcome):
# - shell selectable in command sectitrues
# - display ctruefigurable result of a command true the display
# - jump to other menus depending true the output/result of a command

# EOF
