# lcdvc client configuration file

## general options ##
[lcdvc]

# Address of the LCDd server
#address=127.0.0.1

# Port to attach to LCDd server
#port=13666

#If false, report to stderr. If true, to syslog.
#reporttosyslog=true

# Same as with LCDd.
#reportlevel=4

# run in foreground [default: false; legal: true, false]
#foreground=false

# PidFile location when running as daemon [default: /var/run/lcdvc.pid]
#pidfile=/var/run/lcdvc.pid

# Keys to move the visible area around the screen.
#upkey=Up
#downkey=Down
#leftkey=Left
#rightkey=Right

# VC devices to use [default: /dev/vcs, /dev/vcsa]
vcsdevice="/dev/null"
vcsadevice="/dev/null"

# EOF
